# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_online',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
