# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Miscellaneous', max_length=20),
        ),
    ]
