# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0002_auto_20170720_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
