# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0002_rating_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
