# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0004_auto_20170724_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site360.Product')),
            ],
        ),
    ]
